### ISSUE TITLE
SAPT for element Ag and Ni

### ISSUE THREAD

**Issue by autolife** [psi4/psi4public#105]
firstly ,I found  def2-qzvppd basis set is fit  for element Ag and Ni in the EMSL website.  So I choose the basis set in the psi4.
it successed for the molecule include Ni element.
but it failed for the molecule include Ag element.

---
Gaussian94B::parser: Unable tosis set for AG in /ufor AG in/u4/share/psie/basis/dzpsi/dz...

**Comment by autolife** [comment]
sto-3g basis set is fit for the element Ag;
but it failed again for molecule include Ag element.

**Comment by ryanmrichard** [comment]
Using the Def2-QZVPPD basis for Ag requires an effective core potential (ECP).  ECPs are not currently supported in Psi4.  STO-3G, on the other hand, should work for Ag as that does not require an ECP.  Can you attach the output that is failing in that scenario?

**Comment by mberdakin** [comment]
Hi, I'm new with Psi4 so my problem could be a little naive, I'm dealing with a similar issue than @autolife , when I try to run the energy calculation of a silver containing molecule, I get stuck with basis set error (STO-3G). In the following lines I have pasted a simplified input.in and the error message.   

Thanks in advance 
Matias  

----------------------------------------
molecule {
1 1
 Ag                 0.37900000   -2.54600000    8.09100000
}

set basis sto-3g
energy('df-mp2')
set molden_write true

property('df-mp2', properties=['MULLIKEN_CHARGES'])
--------------------------------------

qcdb.exceptions.BasisSetNotFound: BasisSet::construct: Unable to find a basis set for atom 1 for role JKFIT among:
  Shell Entries: ['AG']
  Basis Sets: ['cc-pvdz-ri', 'def2-qzvpp-jkfit']
  File Path: , /home/matias/anaconda/share/psi/basis
  Input Blocks:

**Comment by ryanmrichard** [comment]
@loriab can correct me if I'm mistaken, but I think your error is occurring because STO-3G doesn't have a fitting basis.  Try using one of our "hidden" features, conventional, non-DF MP2; details on how to do this can be found at this link:
http://www.psicode.org/psi4manual/master/occ.html
,but amount to replacing `'df-mp2'` with `'conv-mp2'`

**Comment by mberdakin** [comment]
Hi, thanks for answering in a such a short period of time.
Changing df-mp2 for conv-mp2 doesn't seems to solve the problem.
Maybe I misunderstood, but I thought that cc-pvdz-ri was the auxiliary basis set for STO-3G.

**Comment by jturney** [comment]
There is no cc-pVDZ basis for Ag. That's the problem.

Justin Turney, Ph.D.
Senior Research Scientist
CCQC/UGA

**Comment by loriab** [comment]
STO-3G doesn't have a fitting basis of its own, but it does fall back on cc-pvdz-ri and then def2-qzvpp-jkfit when a fitting basis is needed. The problem is the silver. From http://psicode.org/psi4manual/master/basissets_byelement.html, you'll see that psi4 basis sets end with krypton. That's because even though the fitting basis of last resort (the def2 one) is defined throughout the periodic table on EMSL, anything past krypton needs effective core potentials (ECPs) and psi4 just doesn't have those. It's a feature we'd all like, just haven't had a research motivation to implement.

**Comment by ryanmrichard** [comment]
As the above posts have stated Ag is your problem.  That being said STO-3G is defined for Ag, without an ECP, so the calculation you are trying to do should work with the correct set of options (and if it doesn't that's a bug).  I suspect the problem is that conv-mp2 is still trying to use a DF-HF reference, so let's turn that off too.  Try this input:

```
molecule {
1 1
Ag 0.37900000 -2.54600000 8.09100000
}

set{
 basis sto-3g
df_scf_guess false
scf_type direct
guess sad
}
energy('conv-mp2')
set molden_write true
```

**Comment by mberdakin** [comment]
Ok, understood 
Thanks you very much for your help.

**Comment by mberdakin** [comment]
Ok
I will try with your input

**Comment by mberdakin** [comment]
I don't want to take more of your time.
I tried the input that you sent me and the calculation ends with the following error

--------------------------------------

PSIO_ERROR: Can't find TOC Entry IWL Buffers
PSIO_ERROR: unit = 33, errval = 13
PSIO_ERROR: 13 (no such TOC entry)
Traceback (most recent call last):
  File "<string>", line 23, in <module>
  File "/home/matias/anaconda/share/psi/python/driver.py", line 637, in energy
    procedures['energy'][lowername](lowername, **kwargs)
  File "/home/matias/anaconda/share/psi/python/proc.py", line 582, in run_mp2
    run_conv_omp2(name, **kwargs)
  File "/home/matias/anaconda/share/psi/python/proc.py", line 538, in run_conv_omp2
    psi4.occ()
RuntimeError: PSIO Error

------------------------------------

In the input you used some keywords that i'm not familiar with, so i have to study the manual a little more, to understand the error.

**Comment by jturney** [comment]
Change:

scf_type pk

Justin Turney, Ph.D.
Senior Research Scientist
CCQC/UGA

**Comment by mberdakin** [comment]
ok, now I owe several beers.
With the last correction it worked!!.
Thanks you very much for your time

**Comment by mberdakin** [comment]
Now I have to understand what that input does :p

**Comment by loriab** [comment]
It's not too complicated. The below is equivalent and slightly preferred.

```
set {
    basis sto-3g        # minimal orbital basis set
    df_scf_guess false  # usually, psi4 saves time by doing most of the HF iterations using density fitting then only a few with the full integrals. Since fitting basis sets aren't available, this skips the density fitting iterations.
    scf_type direct     # selects a non-density-fitting algorithm for the HF
    guess sad           # a better guess to start the HF iterations; sad is nearly always the best guess
    mp2_type conv       # selects a non-density-fitting algorithm for the MP2
}
energy('mp2')
```

**Comment by jgonthier** [comment]
But remember to use 
scf_type pk

The conventional MP2 code does not support scf_type direct yet... Briefly, PK stores integrals on disk, whereas direct recomputes them as needed (at least I believe so).

**Comment by mberdakin** [comment]
Ok 
thanks you very much for the patience and the information
