### ISSUE TITLE
fix failing test case opt-lindep-change

### ISSUE THREAD

**Issue by psi4** [psi4/psi4public#125]

**Comment by kannon92** [comment]
This test case is failing.  Optking says that the test case does not converge.

**Comment by ryanmrichard** [comment]
The test case is trying to figure out whether or not a linear dependency messes up the calculation.  It appears that the linear dependency is not messing up the calculation and the issue is that the final energies do not match.  At some point the optimizer must have changed and as a result the energies no longer match to five decimal places, but rather to only three.  I loosened the check to three decimal places.  Commit 3bc5f146dfbbc6a09d9ccbe034f2ffdd7d32d6e9 fixes this.
