### ISSUE TITLE
Sphinx documentation installation overwrites files in source tree (samples/)

### ISSUE THREAD

**Issue by mbanck** [psi4/psi4public#14]
If I build psi4 and then run make distclean, I do not get the initial tarball content again, as the script doc/sphinxman/document_tests.pl overwrites samples/SUMMARY and some samples with new content. This makes Debian source package building fail after a build:

dpkg-source: info: local changes detected, the modified files are:
 psi4.0b5/samples/SUMMARY
 psi4.0b5/samples/dcft1/input.dat
 psi4.0b5/samples/dcft4/input.dat
 psi4.0b5/samples/dcft5/input.dat
 psi4.0b5/samples/dcft6/input.dat
 psi4.0b5/samples/pywrap-alias/input.dat

I think it would be best if (i) the samples are written to the builddir, or (ii) the samples are not shipped in the tarball in the first place, assuming all of samples/ is being autogenerated during doc-creation/installation anyway.

**Comment by psi4** [comment]
``samples/SUMMARY`` which was the major offender was removed some time ago. If someone's added a test to ``tests``, the attendant ``samples`` file doesn't get updated automatically. Perhaps a post-commit hook is in order to make that happen. Basically, we want samples to never be out of date so that a make, make docs doesn't add anything outside the objdir.

**Comment by loriab** [comment]
No change since the last comment, but I'm satisfied that `samples/SUMMARY` is gone, and packagers can work from particular tags that we've been careful to add new samples/*/input.dat 's for.
