### ISSUE TITLE
Orbital plotting example in manual

### ISSUE THREAD

**Issue by CDSherrill** [psi4/psi4public#142]
Extend Francesco's documentation on writing cube files to explain how to actually plot orbitals using VMD or similar software.  Consider adding Evangelista group VMD script to Psi4 source.  Assigned to Wallace.

**Comment by jeffschriber** [comment]
This issue can now be closed.

**Comment by fevangelista** [comment]
Thanks Jeff for creating the documentation.  There is one little problem to fix: the online documentation does not show the MO figure.  @loriab, do you happen to have any suggestion?

**Comment by loriab** [comment]
That's an easy one: needed to copy the image file over from src to build directory via CMake. Also, I changed the order of argument parsing and vmd prep in the script so that ``vmd_cube.py --help`` works. _Please_ make sure this is ok to do. Finally, I used the argparse output as an alternate Options section in the sphinxman/source/cubeprop.rst , as that might be easier to maintain. So just choose which and delete the other.

**Comment by fevangelista** [comment]
Thanks @loriab!  Switching the arguments is fine and I like the idea of using the output of argparse for the options section.  We'll delete the other options.

**Comment by loriab** [comment]
Great. And it looks like everything in `lib/scripts` gets installed, so no special action needed there.

**Comment by fevangelista** [comment]
Ok, all is ready for shipping.
