### ISSUE TITLE
Confusing documentation for stability analysis

### ISSUE THREAD

**Issue by kannon92** [psi4/psi4public#181]
I was trying to run a stability analysis for the SCF codes.  In the documentation, there are two places where the stability analysis is mentioned.  

 The first is mentioned in the stability section of the documentation: http://www.psicode.org/psi4manual/master/autodir_options_c/module__stability.html?highlight=stability

This keyword does not seem to work.  I try set stability follow true and there is no stability analysis.

The second is mentioned here: 
http://www.psicode.org/psi4manual/master/autodir_options_c/scf__stability_analysis.html?highlight=stability_analysis  

The second keyword is to say stability_analysis (NONE, CHECK, FOLLOW) and this does provide a stability analysis.  However, I do not think that CHECK or FOLLOW actually do anything.  The code just checks to see if stability_analysis is not NONE.

**Comment by jgonthier** [comment]
The stability module documentation that you mention first is auto-generated because there is a stability module, however it is apparently not used at all anymore. I planned to delete it but did not get to it yet. Once the module will be deleted, the corresponding auto-generated documentation will disappear as well.

The second documentation is the one I wrote after I included the new UHF->UHF stability. Please let me know if there is anything you'd wish me to change or improve in this document.
The code just checks if stability_analysis is not NONE at the beginning. The difference between CHECK and FOLLOW appears within the UHF procedure for now, see https://github.com/psi4/psi4public/blob/master/src/lib/libscf_solver/uhf.cc

Do you see any problem with one of these options?

**Comment by jgonthier** [comment]
Deleted the stable module and corresponding options in the private branch (see adef710b4316a870e9df205338e3b82efebc6629). I'll do the public one tonight, and then close the issue if there are no other concerns.

**Comment by kannon92** [comment]
I am sorry about this.  I didn't realize you wrote some documentation about this.  I should read the manual and read a little more about what stability analysis is trying to do.

**Comment by jgonthier** [comment]
No worries, you gave me the push I needed to finally clean up this code. I deleted the stable module in the public version as well now (see 1973ccd343aacde33736cc3a4df1d0e84be05887 ).
