### ISSUE TITLE
Error when making libmints

### ISSUE THREAD

**Issue by kimt33** [psi4/psi4public#188]
Hello. I was trying to build Psi4 onto a cluster and I encountered this error:
```
$psisource/src/lib/libmints/oeprop.h(116): error: data member initializer is not allowed
      int max_noon_ = 3;

compilation aborted for /work/kimt33/sources/psi4/src/lib/libmints/local.cc (code 2)
make[2]: *** [src/lib/libmints/CMakeFiles/mints.dir/local.cc.o] Error 2
make[1]: *** [src/lib/libmints/CMakeFiles/mints.dir/all] Error 2
make: *** [all] Error 2
```

I was told by my Linux guru to try different compilers and libraries in case that the code is incompatible with my system. I was building using Intel compilers 12.1.3, mkl 10.3.9, openmpi 1.6.2, cmake 3.3.2, python 2.7.8, and boost 1.57.0. I'm not too sure what the error means, but maybe this is a bug. Let me know if you'd like more information.

Thanks,
David

**Comment by ryanmrichard** [comment]
Your Linux guru is correct, you will need a newer compiler.  The error is
because your compiler does not support C++11.  Check out:

https://github.com/psi4/psi4public/wiki/9_CXX

for our current C++ compiler requirements.  You may want to just consider
downloading the precompiled binaries, see:

https://github.com/psi4/psi4public/wiki/1_Obtaining#condabinary

for more information.

Hello. I was trying to build Psi4 onto a cluster and I encountered this
error:

$psisource/src/lib/libmints/oeprop.h(116): error: data member
initializer is not allowed
      int max_noon_ = 3;

compilation aborted for
/work/kimt33/sources/psi4/src/lib/libmints/local.cc (code 2)
make[2]: *** [src/lib/libmints/CMakeFiles/mints.dir/local.cc.o] Error 2
make[1]: *** [src/lib/libmints/CMakeFiles/mints.dir/all] Error 2
make: *** [all] Error 2

I was told by my Linux guru to try different compilers and libraries in
case that the code is incompatible with my system. I was building using
Intel compilers 12.1.3, mkl 10.3.9, openmpi 1.6.2, cmake 3.3.2, python
2.7.8, and boost 1.57.0. I'm not too sure what the error means, but maybe
this is a bug. Let me know if you'd like more information.

Thanks,
David

—
Reply to this email directly or view it on GitHub
<https://github.com/psi4/psi4public/issues/188>.

**Comment by amjames** [comment]
I have been meaning to mention this for a while actually. 


If we require c++11, why is there an option in setup to disable c++11 support? Also, why can CMake  revert to the older standard?
 
with intell 13.1, I will see this during the configure step: 
`-- Buggy compiler support for C++11. Using Older Standard.` 

If I edit this line in CMakeCache.txt
`CMAKE_CXX_FLAGS:STRING=-DRESTRICT=__restrict__ -Xlinker -export-dynamic -fPIC -std=gnu++98`
to `-std=c++11` before I make I can build successfully, but if I don't I will get the same errors mentioned above. 

CMake should produce an error if C++11 support is not detected, fail at the configuration step, and report why to the user. I think the current behavior is very confusing.

**Comment by loriab** [comment]
I haven't encountered this behavior myself, but it does sound faulty. Since there's the binary as fallback and more and more pieces are using c++11, I don't think we're avoiding it anymore. @robertodr was talking about the feasibility of using some advanced cmake features to handle this problem more logically (https://cmake.org/cmake/help/v3.1/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html). They will require bumping our required cmake version, but, for developers, that's not so bad.

**Comment by robertodr** [comment]
@jturney could you post a small example of using `target_compile_features`?

**Comment by CDSherrill** [comment]
Now that the Linux binary is now available, I'm comfortable having stronger
C++11 requirements.

David

**Comment by jturney** [comment]
Sorry for taking so long:

    # define library
    add_library(core STATIC ${CORE_SOURCE_FILES} ${CORE_HEADER_FILES})

    # link dependencies
    target_link_libraries(
        core
        ${Boost_LIBRARIES}
        ${ICONV_LIBRARIES}
        ${CORE_SYSTEM_LIBRARIES}
    )

    # This has been sufficient to enable C++11 for me. I should probably explicitly list
    # the features I require.
    target_compile_features(core PUBLIC cxx_constexpr)

Since I stated ```PUBLIC``` on the ```target_compile_features``` targets that depend on ```core``` will require that specific C++11 to be enabled.

**Comment by robertodr** [comment]
@jturney It seems that CMake is not aware of any compiler features for the Intel compilers...
How do you handle this? Or you never tried to compile your other projects with Intel?
I found some "custom" extensions for the Intel compilers, but that would just move the maintenance work from the current detection system to another...

**Comment by ryanmrichard** [comment]
Closing this.  Perhaps this discussion can continue on the C++11 thread on the forum?
