### ISSUE TITLE
--new-plugin-makefile does not work properly with conda

### ISSUE THREAD

**Issue by rmcgibbo** [psi4/psi4public#214]
The `--new-plugin` and `--new-plugin-makefile` generators are a really awesome idea. Unfortunately, they don't quite work properly with the latest conda binaries from `conda install -c psi4 psi4`, because the `Makefile` is generated with absolute paths to the build machine.

For example, I get something like this setting the compiler and include directories in the generated makefile. I assume this works great on your cluster, but no to much on mine:
```
# Flags that were used to compile Psi4.
CXX = /theoryfs2/common/software/intel2015/composer_xe_2015.3.187/bin/intel64/icpc
CXXDEFS = -DHAVE_DKH -DHAVE_MM_MALLOC_H -DHAVE_MKL_LAPACK -DHAVE_MKL_BLAS -DHAS_CXX11_VARIADIC_TEMPLATES -DHAS_CXX11_STATIC_ASSERT -DHAS_CXX11_SIZEOF_MEMBER -DHAS_CXX11_RVALUE_REFERENCES -DHAS_CXX11_NULLPTR -DHAS_CXX11_LONG_LONG -DHAS_CXX11_LAMBDA -DHAS_CXX11_INITIALIZER_LIST -DHAS_CXX11_DECLTYPE -DHAS_CXX11_CSTDINT_H -DHAS_CXX11_CONSTEXPR -DHAS_CXX11_AUTO_RET_TYPE -DHAS_CXX11_AUTO -DHAS_CXX11_FUNC -DHAS_CXX11 -DSYS_LINUX -DUSE_FCMANGLE_H
CXXFLAGS = -DRESTRICT=__restrict__ -Xlinker -export-dynamic -fPIC -std=c++11 -qopenmp -O3 -no-prec-div -DNDEBUG
LDFLAGS = -static-libstdc++ -static-libgcc -static-intel -wd10237 -static-intel -L/theoryfs2/ds/cdsgroup/psi4-compile/nightly/glibc2.12/usr/lib64 /theoryfs2/ds/cdsgroup/psi4-compile/nightly/glibc2.12/lib64/libpthread.so.0 /theoryfs2/ds/cdsgroup/psi4-compile/nightly/glibc2.12/lib64/libc.so.6
INCLUDES = -I/scratch/cdsgroup/conda-builds/work/build/interfaces/include -I/scratch/cdsgroup/conda-builds/work/build/src/lib -I/scratch/cdsgroup/conda-builds/work/src/lib -I/scratch/cdsgroup/conda-builds/work/include -I/scratch/cdsgroup/conda-builds/work/build/include -I/scratch/cdsgroup/conda-builds/work/build/boost/include -I/home/rmcgibbo/miniconda/envs/2.7/include/python2.7 -I/usr/include -I/usr/include -I/usr/include -I/usr/include
OBJDIR = /scratch/cdsgroup/conda-builds/work/build
```

**Comment by rmcgibbo** [comment]
... also, `libplugin` is completely missing from the package...

**Comment by loriab** [comment]
Yes, the plugin scheme as currently implemented expects that you're generating a new plugin from a locally compiled psi4. The binary clearly doesn't satisfy that and indeed the excerpt you posted is both machine- and build-specific since it contains various oddities for making the binary as static and backwards-compatible as possible.

I'm actually in the middle of trying to get the psi4 binary and all its subsidiaries in shape for both users and developers. May as well try to get plugins going, too. If you know of any conventions for handling plugins/libgcc dependencies within conda, I'd be interested to read of them.

Where is `libplugin` called for? In the build, it's just a static library that gets linked into the psi4 exe. I can certainly install it, but it may need to be a `.so`  to be useful.

**Comment by rmcgibbo** [comment]
> Where is libplugin called for?

I'm not 100% sure if this is necessary or not -- I was trying to adapt my old plugin from a couple years ago (for RESP charge fitting) that no longer compiles, so that might be just accidental on my part.

**Comment by rmcgibbo** [comment]
> If you know of any conventions for handling plugins/libgcc dependencies within conda...

The default anaconda channel includes a libgcc, so you can declare a depenency on it. I assume you've considered that and it's the wrong version or something? Generally, you don't need to have everything statically linked in conda, since you can either provide shared libraries in your package or depend on other packages that include shared libraries, and everything will be patched up with `RPATH`s.

**Comment by loriab** [comment]
A couple of years ago, psi4 was on GnuMake or 1st iteration CMake build system, so plugin building (at least the `Makefile` spit out) has definitely been updated since then.

Yes, I've been eyeing the libgcc conda package. Haven't tried it yet because I was so pleased to get the psi4-only binary down to only lc, ldl, lpthread, lrt, lutil system libraries. But it seems that some dynamic libgcc dependency may be necessary to assemble psi4 and add-ons and dependencies from other conda channels, so I'll likely give in soon.

Fortunately, that plugin Makefile is just a template (https://github.com/psi4/psi4public/blob/master/lib/plugin/Makefile.template), so if I can get plugins working development-environment-wise, adjusting the ``--new-plugin-makefile`` output won't be a problem.

**Comment by jturney** [comment]
I can work on this if you want. Also, Libplugin shouldn't be needed anymore.

Justin

**Comment by loriab** [comment]
I started in on this last night. The scheme for generating a Makefile from from a locally compiled psi4 exe can stay as it is, I think. Though we should make it so that it can be generated from an installed copy alone. Key missing component of that is that the main `$psi4-clone-dir/includes/*h` header files don't get installed at the moment. The `$psi4-clone-dir/src/*/*/*.h` files do. Do you think the lot should go behind a namespace like `$psi4-install-dir/includes/psi4/psifiles.h` (or `psi`)? Boost headers may also need to be installed.

The other part is to make it so that people can check out plugins from the conda exe. I suppose the proper way to do this would be to have plugins under CMake control so that it would go off and detect their compiler/math situation. But instead I was thinking of sticking with Makefile and forcing the build environment– just setting it up so that generated plugins are ready to be compiled with conda gcc and math libs. The below is a start.

```
# Flags that were used to compile Psi4.
MCONDA = /theoryfs2/ds/cdsgroup/psi4-install/miniconda/envs/p4plug  # set by $PREFIX
CXX = ${MCONDA}/bin/g++
INCLUDES = -I${MCONDA}/include/ -I${MCONDA}/include/psi4 -I${MCONDA}/include/python2.7 -I/usr/include
```

How does that seem for a plan? @jturney, if you'd like to work on this, that'd be great. Or if you want me to do the conda parts, I'd be glad to do so.

**Comment by loriab** [comment]
Ok, if one installs into a conda env the packages `psi4` (from us), `gcc`, and `openblas` (from default/anaconda channel), check out a new plugin from that psi4 exe, and modify the Makefile as below, it should work. 

```
# miniconda environment
MCONDA = /theoryfs2/ds/cdsgroup/psi4-install/miniconda/envs/p4plug
# Flags that were used to compile Psi4.
CXX = ${MCONDA}/bin/g++
CXXDEFS = -DHAVE_DKH -DHAVE_MM_MALLOC_H -DHAS_CXX11_VARIADIC_TEMPLATES -DHAS_CXX11_STATIC_ASSERT -DHAS_CXX11_SIZEOF_MEMBER -DHAS_CXX11_RVALUE_REFERENCES -DHAS_CXX11_NULLPTR -DHAS_CXX11_LONG_LONG -DHAS_CXX11_LAMBDA -DHAS_CXX11_INITIALIZER_LIST -DHAS_CXX11_DECLTYPE -DHAS_CXX11_CSTDINT_H -DHAS_CXX11_CONSTEXPR -DHAS_CXX11_AUTO_RET_TYPE -DHAS_CXX11_AUTO -DHAS_CXX11_FUNC -DHAS_CXX11 -DSYS_LINUX -DUSE_FCMANGLE_H
CXXFLAGS = -DRESTRICT=__restrict__ -Xlinker -export-dynamic -fPIC -std=c++11 -fopenmp -O3 -DNDEBUG -Wno-unused
LDFLAGS =
LDFLAGS="-Wl,-rpath,${MCONDA}/lib/"
INCLUDES = -I${MCONDA}/include/ -I${MCONDA}/include/psi4 -I${MCONDA}/include/python2.7 -I/usr/include
```

more explicitly,

```
conda create -n p4plug2 psi4
source activate p4plug2
cd p4plug2  # may vary; just get into the miniconda/envs/p4plug2 directory
conda install gcc  # 4.8.5-3
psi4 --new-plugin testplug
cd testplug
vi Makefile  # copy in Makefile mods above, changing MCONDA variable
cp -pR ../../p4plug/include/psi4/ ../include/  # copy in a set of psi4 headers
make
psi4  # run sample input.dat
ldd testplug.so 
	linux-vdso.so.1 =>  (0x00007fff969fe000)
	libstdc++.so.6 => /theoryfs2/ds/cdsgroup/psi4-install/miniconda/envs/p4plug2/lib/libstdc++.so.6 (0x00007f763d984000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f763d65c000)
	libgcc_s.so.1 => /theoryfs2/ds/cdsgroup/psi4-install/miniconda/envs/p4plug2/lib/libgcc_s.so.1 (0x00007f763d446000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f763d085000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f763de9e000)
```

@jturney, if you approve the plan, do you want to fix the includes installation and trigger an alternate Makefile.template if binary?

**Comment by rmcgibbo** [comment]
What are the expected compiler requirements here? Is it actually necessary to use the conda `gcc`?

**Comment by rmcgibbo** [comment]
For my use case, I have actually not been using the `psi4`-generated Makefile directly. What I've been doing is generating the Makefile in a temporary directory and parsing it to extract the `CXXDEFS` / `CXXFLAGS`, linker options, include directories, and so forth, and then generating my own makefile using that information.

So from this perspective, what would be really useful is something that lets me get that information out. For example, `libnetcdf` (https://packages.debian.org/sid/libnetcdf-dev) always ships with an executable called `nc-config` that you can query for this information. So if possible (feature request, I guess), something similar for the plugin mechanism would be ideal

```
$ nc-config --cflags
-I/Users/rmcgibbo/miniconda/envs/3.5/include
rmcgibbo@MacBook-Pro  ~ (3.5)
$ nc-config --libs
-L/Users/rmcgibbo/miniconda/envs/3.5/lib -lnetcdf
```

**Comment by loriab** [comment]
It's not necessary to use the conda `gcc`– just that makes for a predictable `Makefile`. I'll investigate `nc-config`. It always helps to know use cases, thanks.

**Comment by rmcgibbo** [comment]
@loriab, okay, I think I got my plugin compiling against the latest psi4 conda build. The code is [here](https://github.com/rmcgibbo/resp2) and the build log on Travis-CI [here](https://travis-ci.org/rmcgibbo/resp2), if you're curious, at least about the configure/make stuff.

**Comment by loriab** [comment]
Nice! If you're allowing general use, that might even cross off the lingering 'add RESP to psi4' ticket (https://github.com/psi4/psi4/issues/20).

I've added a `bin/psi4-config` script to the installation, final contents (for the binary) below. Binary nightly build is off for the moment, because I'm working on it for other reasons, but you can see if something like the below is what you'd like. I'm concerned that it's got a lot of full paths and binary-specific (static) flags and libraries, but perhaps it can be made useful with some modifications.

```py
#!/usr/bin/env python
# vim:ft=python

import sys
from collections import OrderedDict


def main(argv):
    info = OrderedDict()
    info['--cc'] = '/theoryfs2/common/software/intel2015/composer_xe_2015.3.187/bin/intel64/icc'
    info['--cxx'] = '/theoryfs2/common/software/intel2015/composer_xe_2015.3.187/bin/intel64/icpc'  # aka PLUGIN_CXX
    info['--fc'] = '/theoryfs2/common/software/intel2015/composer_xe_2015.3.187/bin/intel64/ifort'
    info['--version'] = psiver
    info['--githash'] = githash
    if 'ON' == 'ON':
        info['--prefix'] = '/opt/anaconda1anaconda2anaconda3'
    else:
        info['--prefix'] = '/theoryfs2/ds/cdsgroup/psi4-install/miniconda/envs/_build_placehold_placehold_pl'
    info['--top-level-psi4-dir'] = '/scratch/cdsgroup/conda-builds/work'
    info['--max-am-eri'] = '4'
    info['--python-version'] = '2.7'
    info['--has-pcmsolver'] = 'ON'
    info['--has-chemps2'] = 'ON'
    info['--includes'] = '-I/scratch/cdsgroup/conda-builds/work/build/interfaces/include -I/scratch/cdsgroup/conda-builds/work/build/src/lib -I/scratch/cdsgroup/conda-builds/work/src/lib -I/scratch/cdsgroup/conda-builds/work/include -I/scratch/cdsgroup/conda-builds/work/build/include -I/scratch/cdsgroup/conda-builds/work/build/boost/include -I/theoryfs2/ds/cdsgroup/psi4-install/miniconda/envs/_build_placehold_placehold_pl/include/python2.7 -I/usr/include -I/usr/include -I/usr/include -I/usr/include'  # aka PLUGIN_INCLUDES
    info['--defines'] = '-DHAVE_PCMSOLVER -DHAVE_DKH -DHAVE_MM_MALLOC_H -DENABLE_CHEMPS2=1 -DHAVE_MKL_LAPACK -DHAVE_MKL_BLAS -DHAS_CXX11_VARIADIC_TEMPLATES -DHAS_CXX11_STATIC_ASSERT -DHAS_CXX11_SIZEOF_MEMBER -DHAS_CXX11_RVALUE_REFERENCES -DHAS_CXX11_NULLPTR -DHAS_CXX11_LONG_LONG -DHAS_CXX11_LAMBDA -DHAS_CXX11_INITIALIZER_LIST -DHAS_CXX11_DECLTYPE -DHAS_CXX11_CSTDINT_H -DHAS_CXX11_CONSTEXPR -DHAS_CXX11_AUTO_RET_TYPE -DHAS_CXX11_AUTO -DHAS_CXX11_FUNC -DHAS_CXX11 -DSYS_LINUX -DUSE_FCMANGLE_H'
    info['--ldflags'] = ' -static-libstdc++ -static-libgcc -static-intel -wd10237 -static-intel'  # aka PLUGIN_LDFLAGS. skipping LIBC_INTERJECT
    info['--flags'] = '-DRESTRICT=__restrict__ -Xlinker -export-dynamic -fPIC -std=c++11 -qopenmp -O3 -no-prec-div -DNDEBUG'  # aka PLUGIN_FLAGS
    info['--libs'] = sep_cmake_list('-Wl,--start-group;/theoryfs2/common/software/intel2015/composer_xe_2015.3.187/mkl/lib/intel64/libmkl_intel_lp64.a;/theoryfs2/common/software/intel2015/composer_xe_2015.3.187/mkl/lib/intel64/libmkl_intel_thread.a;/theoryfs2/common/software/intel2015/composer_xe_2015.3.187/mkl/lib/intel64/libmkl_core.a;/lib64/libpthread.so;/lib64/libm.a;-openmp;-Wl,--end-group;-Wl,--start-group;/theoryfs2/common/software/intel2015/composer_xe_2015.3.187/mkl/lib/intel64/libmkl_lapack95_lp64.a;/theoryfs2/common/software/intel2015/composer_xe_2015.3.187/mkl/lib/intel64/libmkl_intel_lp64.a;-openmp;-Wl,--end-group')

    if len(argv) == 1:
        retstr = """Build conditions of Psi4. Usage:
>>> psi4-config --all
>>> psi4-config --flags --libs
"""
    elif argv[1] == '--all':
        retstr = ''
        for k, v in info.iteritems():
            retstr += """%-20s --> %s\n""" % (k, v)
    else:
        retstr = []
        for arg in sys.argv[1:]:
            retstr.append(info[arg])
        retstr = ' '.join(retstr)

    return retstr


def sep_cmake_list(cmlist):
    return ' '.join(cmlist.split(';'))


if __name__ == '__main__':
    pass
    psiver = "0.3.479"
    githash = "{master} 9a95002 "
    sys.exit(main(sys.argv))

```

**Comment by rmcgibbo** [comment]
- Very cool. I'm not sure exactly if I'd be able to make that work for my plugin, because so many of the things are still either `icc/icpc` specific or tied to your build machine, but it will make getting the info out easier.
- Using conda's `info/has_prefix` / string replacement stuff for relocatable build, I assume some of strings will get modified on installation to point to the proper place.
- I'm not a collaborator on the psi4/psi4 issue tracker, so I can't see that issue. But if anyone on your team wants to take the RESP plugin and modify or improve it, that would be great.

**Comment by rmcgibbo** [comment]
In particular, is it necessary to include `-DRESTRICT=__restrict__ -Xlinker -DNDEBUG` in the `flags`, instead of with the other defines? Since `flags` includes `-qopenmp` and `-no-prec-div`, which i can't use with g++, I was just leaving that out. But the `defines` flags are general to any compiler.

**Comment by loriab** [comment]
* I don't know about those defines, though @robertodr might. They're per-compiler specified, and flags may have been set up that way but defines not.
* I just wanted to get the issue linked. It doesn't say much.
* Only prefix is really set up for the relocatable substitution at the moment. Will set about doing more. Or could export the gcc Makefile lines from earlier.

**Comment by robertodr** [comment]
@rmcgibbo is right. Those definitions should go into the `--defines` and not into the compiler flags.

**Comment by loriab** [comment]
starting with conda psi4 `0.3.491`, you should be getting all the headers (though not namespace protected) and the basic `psi4-config` script.

**Comment by rmcgibbo** [comment]
> starting with conda psi4 0.3.491, you should be getting all the headers (though not namespace protected) and the basic psi4-config script.

There's one missing header, which is `psi4config.h`. conda psi4 0.3.491 includes `include/psiconfig.h.cmake.in`, but not the fully configured `include/psiconfig.h`.

**Comment by loriab** [comment]
Ok, conda psi4 `0.3.530` should have `psi4config.h` among `include/psi4/*.h`.

**Comment by rmcgibbo** [comment]
This is great. All of my plugin compilation stuff is working now with the latest conda release, so I'm going to close this. Thanks for all the hard work!

**Comment by loriab** [comment]
Great, thanks for the motivation to get it working.
