### ISSUE TITLE
Question about plugin "installation"

### ISSUE THREAD

**Issue by rmcgibbo** [psi4/psi4public#229]
Hi,

Since 0.3.530 or so, all of the difficulties that I've had about compiling plugins have been worked out. I'm sure there are other possible schemes, but the one I have now is a `configure` shell script that writes a `Makefile` using some information from the new `psi4-config` ([link](https://github.com/rmcgibbo/resp2/blob/master/configure)).

The remaining plugin-related question I have now is about "installation". If I want to distribute this plugin to other users (it's really just the `<plugin_name>.so` file, I don't have any obligatory Python code), and make it easy for them to install, I'd like to make something like `conda install -c rmcgibbo <my_plugin>` work.

If this were a standard Python module, I'd install the package with a Pyton wrapper to `lib/python2.7/site-packages/`, since that'll definitely be on `sys.path` -- is that what I should do here too? Or is there an alternative more psi4-specific location in `share/psi4/` where they would ideally go?

**Comment by loriab** [comment]
So the closest thing we have to precedent on this is the csx4psi plugin (which has nothing to do with dmrg) https://anaconda.org/psi4/csx4psi . More later.

**Comment by rmcgibbo** [comment]
```
$ wget https://anaconda.org/psi4/csx4psi/0.0.8/download/linux-64/csx4psi-0.0.8-0.tar.bz2

$ tar -tjvf csx4psi-0.0.8-0.tar.bz2 
-rw-r--r-- cdsgroup/sherrill 170 2015-09-03 20:23 info/README.md
-rw-r--r-- cdsgroup/sherrill 180 2015-09-03 20:23 info/files
-rw-r--r-- cdsgroup/sherrill 442 2015-09-03 20:23 info/git
-rw-r--r-- cdsgroup/sherrill 193 2015-09-03 20:23 info/index.json
-rw-r--r-- cdsgroup/sherrill 857 2015-09-03 20:23 info/recipe.json
-rw-r--r-- cdsgroup/sherrill 1404 2015-09-03 20:23 info/recipe/build.sh
-rw-r--r-- cdsgroup/sherrill  683 2015-09-03 20:23 info/recipe/meta.yaml
-rwxr-xr-x cdsgroup/sherrill 1319008 2015-09-03 20:23 lib/libiomp5.so
-rw-r--r-- cdsgroup/sherrill     170 2015-09-03 20:23 psi4aux/csx4psi/README.md
-rw-r--r-- cdsgroup/sherrill    1158 2015-09-03 20:23 psi4aux/csx4psi/__init__.py
-rw-r--r-- cdsgroup/sherrill  559469 2015-09-03 20:23 psi4aux/csx4psi/csx1_api.py
-rw-r--r-- cdsgroup/sherrill    3063 2015-09-03 20:23 psi4aux/csx4psi/csx4psi.cc
-rwxr-xr-x cdsgroup/sherrill 1037802 2015-09-03 20:23 psi4aux/csx4psi/csx4psi.so
-rw-r--r-- cdsgroup/sherrill   22479 2015-09-03 20:23 psi4aux/csx4psi/pymodule.py
```

Interesting.

**Comment by loriab** [comment]
So the main control for finding non-distributed things (basis sets, plugins, etc.) in psi4 is the `PSIPATH` environment variable (http://psicode.org/psi4manual/master/external.html#envvar-PSIPATH) that (for python things) internally prepends to `sys.path`.

How to handle user-enabled non-distributed things in a certain place (as conda needs) without `PSIPATH` (or with that dir standardly appended to `PSIPATH`) hasn't really been thought through. (Though now is the time, for you and others that are non-standard at present.) I don't think `share/psi4` is right because that dir is supposed to be platform independent, so `.so` not suitable. Hence I tentatively selected `psi4aux`. I've done a little internet searching but not much inspection of unpacked conda packages seeking a precedent.

**Comment by rmcgibbo** [comment]
Is there a problem that you're aware of with putting it in site-packages/, as one one do with a regular Python package?

**Comment by loriab** [comment]
Installing user add-ons into the normal tree would be alarming for things like basis sets into `share/psi4/basis` because that could deviously rename common data. But talking it over with a few people, we think that the normal installation tree is fine for conda packages with binaries going to `bin` and python packages going to `lib/python-2.7/site-packages`.

**Comment by loriab** [comment]
Resolution: for the conda installation environment, so long as not overwriting distributed file (e.g., no renaming S22 database or cc-pvdz basis set), install into normal location on install tree. Reopen if further questions.

**Comment by rmcgibbo** [comment]
Cool. Thanks @loriab for all your help!

**Comment by loriab** [comment]
Glad to help, as you're actually using the feature. Note that we're doing some infrastructure reworking (on private repo for now, but private is what conda builds from, again for now) that affect plugins. Until that settles down and appears in public (which is to become our primary repo, for conda, too) with guidelines, you may want to stick with recommending the `0.3` series for your RESP plugin. (Helps that our nightly build box is down for now, so there's only one `0.4` series around https://anaconda.org/psi4/psi4/files.)
