### ISSUE TITLE
Zero-length file src/lib/attic/libyeti/dataimpl.h

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4public#5]
The file src/lib/attic/libyeti/dataimpl.h is zero-length. Could it be removed?

**Comment by psi4** [comment]
Now no longer zero-length, it has license text! You're right that the file is useless, but it's an implementation stub, and it's in the attic and unused, so I'm leaving it be rather than deleting it and changing a dozen files to remove the header include. If this is still a problem, reopen the issue, and I'll see what can be done.
