### ISSUE TITLE
outfile

### ISSUE THREAD

**Issue by SebWouters** [psi4/psi4public#77]
Dear all,

Previously - when outfile was a "FILE *" - I redirected my output stream to psi4's stream as follows:

    ** stuff in plugin **
    
        std::ofstream psi4outfile;
        std::streambuf * cout_buffer;
        if ( outfile_name != "stdout" ){
            fclose(myoutfile);
            myoutfile = NULL;
            psi4outfile.open( outfile_name.c_str() , ios::app ); // append
            cout_buffer = cout.rdbuf( psi4outfile.rdbuf() );
        }
    
    ** stuff in my code **
    
        if ( outfile_name != "stdout" ){
            cout.rdbuf(cout_buffer);
            psi4outfile.close();
            myoutfile = fopen(outfile_name.c_str(), "a");
            if (myoutfile == NULL){
                throw PSIEXCEPTION("PSI4: Unable to reopen output file.");
            }
        }
    
    ** stuff in plugin **

The original plugins can be found here:
https://github.com/SebWouters/CheMPS2/blob/master/integrals/psi4plugins/dmrgci.cc
https://github.com/SebWouters/CheMPS2/blob/master/integrals/psi4plugins/dmrgscf.cc

Which way would you prefer to redirect C++'s cout to the psi4 outfile now?

Thank you!
Best,
Sebastian

**Comment by ryanmrichard** [comment]
Sebastian, my apologies for the forthcoming long response, which probably goes far beyond the answer you need.  However, this question seems common enough that I wanted to write a thorough response that we could then link to in the future when it inevitably comes up again.  That being said a disclaimer of sorts is in order.  The comments herein are meant to be helpful to a wide reaching audience and many may not be directly applicable to you.  Additionally, the comments should not be thought of as targeting you (with the obvious exception being that this post will tell you how to actually print).

Since the decision to prepare/adapt Psi4 for/to MPI parallelism, it has become essential to micromanage resources (presently circularly defined as any aspect of normal program execution that the program may want to control, including, but not limited to: printing, memory, disk, threads, MPI processes) in a more controlled manner than before.  One of these resources is the output.  Under the MPI paradigm, each process generates its own output and Psi4 is hence responsible for ensuring that the output is logged in a logical manner (i.e. you don't get the same output, once for each processes, in the same file, in an incomprehensible mess).  

In a traditional object-oriented coding paradigm, each problem is handled by a dedicated object, and the problem of printing is no exception.  Therefore, within Psi4 we have created the `psi::PsiOutStream` class, of which `psi::outfile` is an instance.  Of particular importance `psi::outfile` is an instance that always redirects output to where the user asked.  To use `psi::outfile` in your code, ensure `#include "psi4-dec.h"` is at the top of your file and then proceed in one of two manners: :
```c++
#include "psi4-dec.h"
//Option 1 (takes the same format strings as C's printf function)
psi::outfile->Printf(<format_string>,<Message>);

//Option 2 (the C++ way)
(*psi::outfile)<<"My Message in C++ form"<<std::endl;
```
The choice of which of these two options to use is largely a matter of preference as internally the class does the same thing.  It's also worth mentioning that there no longer is any reason to worry about flushing the buffer.

In designing a library, that may be potentially used by various codes, the above code is not ideal as it breaks encapsulation by propagating the target program's code throughout the library.    An integral part of library design is establishing an API that allows the library to respect the resource management paradigms of the target codes, but also doesn't lead to a mess of logic statements anytime a resource is needed within the library.  This is best handled by a "wrapper" of some kind.  Within an object-oriented coding paradigm, a (or a series of) resource allocating class(es) would be created.  Then each time your library needs a resource it asks for it from an instance of this/these class(es). Alternatively, a C-like solution is to create a series of wrapper functions; your library then always obtains its resources from these functions. Regardless of which path is taken, the important point is that the specifics of how a target program allocates resources is now encapsulated within some interface, keeping your library clean and agnostic to the details.

For concreteness I provide a C-like solution that provides an interface to Psi4's new outfile instance:
```c++
void MyPrinter(const std::string& Message){
   (*psi::outfile)<<Message;
}

void FxnInMyCodeThatPrints(const int i, const int j){
  std::stringstream Thing2Print;
  Thing2Print<<"The Sum of i, "<<i<<" , and j, "<<j<<" , is: "<<i+j<<std::endl;
  MyPrinter(Thing2Print.str());
}
```
This example is designed to be self-evident, but if it's not the important point is that whenever I go to print in my library I pass the message to the `MyPrinter` function instead of to `std::cout` or a `std::ostream` instance.  The specifics of how the target program prints are then completely encapsulated within the `MyPrinter` function.  Of course this is not the only possible function signature for a wrapper function; in particular, one could also make a `printf` like syntax if desired.

**Comment by SebWouters** [comment]
Hi Ryan,

Capturing cout in a string or stringstream and feeding it to psi::PsiOutStream is OK if the message to be printed is limited in time and volume. If by calling a single function of a library, it executes for a long time and prints a lot of lines over its execution time, it might be good to have a way to intermediary feed them to the psi::PsiOutStream. Else you have to wait till the end of execution to get any information at all. If something goes wrong, you then also don't get an indication where things might have gone wrong.

So is there a possibility to redirect cout's stream directly to psi::outfile, with a continuous output?

**Comment by ryanmrichard** [comment]
The `psi::PsiOutStream` class provides high-level logic that cannot be enforced via/imposed on a `std::streambuf` object and hence `std::cout` can not be redirected to it.  The point of `psi::PsiOutStream` is to micro-manage Psi4's output file in all environments. This simply cannot be done if we allow access to the `std::streambuf` instance within `psi::outfile`, doing so would circumvent the entire point of the `psi::PsiOutStream` class and pave the way for very hard to detect bugs.  If you want to print continuously you will have to redirect your printing via a wrapper or simply pass your printing to `psi::outfile`.
