### ISSUE TITLE
`--version` fails

### ISSUE THREAD

**Issue by wpoely86** [psi4/psi4public#88]
`psi4 --version` gives:
```
(gdb) r
Starting program: /home/ward/tmp/psi4release/build2/bin/psi4 --version
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
std::ostream::sentry::sentry (this=0x7fffffffcea0, __os=...) at /usr/src/debug/gcc-4.9.2-20150212/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/ostream.tcc:51
51	      if (__os.tie() && __os.good())
Missing separate debuginfos, use: debuginfo-install python-libs-2.7.8-9.fc21.x86_64
(gdb) bt
#0  std::ostream::sentry::sentry (this=0x7fffffffcea0, __os=...) at /usr/src/debug/gcc-4.9.2-20150212/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/ostream.tcc:51
#1  0x000000390e699869 in std::__ostream_insert<char, std::char_traits<char> > (__out=..., __s=__s@entry=0x2baeb60 "    ", '-' <repeats 71 times>, "\n", __n=76)
    at /usr/src/debug/gcc-4.9.2-20150212/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/ostream_insert.h:82
#2  0x0000000001e6bd18 in operator<< <std::char_traits<char> > (__s=0x2baeb60 "    ", '-' <repeats 71 times>, "\n", __out=...) at /usr/include/c++/4.9.2/ostream:535
#3  Write2Buffer<char*> (Input=<synthetic pointer>, this=0x0) at /home/ward/tmp/psi4release/src/lib/libparallel/PsiOutStream.h:157
#4  psi::PsiOutStream::Printf (this=0x0, format=format@entry=0x204e9c0 "    ", '-' <repeats 71 times>, "\n") at /home/ward/tmp/psi4release/src/lib/libparallel/PsiOutStream.cc:82
#5  0x00000000008a79bf in psi::print_version () at /home/ward/tmp/psi4release/build2/src/bin/psi4/version.cc:38
#6  0x00000000008e2d57 in psi::psi_start (argc=argc@entry=2, argv=argv@entry=0x7fffffffd798) at /home/ward/tmp/psi4release/src/bin/psi4/psi_start.cc:187
#7  0x0000000000780f3c in main (argc=2, argv=0x7fffffffd798) at /home/ward/tmp/psi4release/src/bin/psi4/psi4.cc:100
```
Done on Fedora 21 with gcc-4.9.2 using 93a5e8d84afd652e6226

`psi4 --help` works fine.

**Comment by loriab** [comment]
I've fixed this, but the changes haven't been synched to psi4public yet. Will do that this week.

**Comment by wpoely86** [comment]
@loriab why do you actually work with a hidden repo? It's quite annoying that all kinds of stuff is fixed/changed but not visible to us.

**Comment by loriab** [comment]
Well, the branches of the hidden repo are so developers can store code that's vulnerable to scientific scooping. And the master of the hidden repo is so we can integrate without being overly concerned about breaking things for people outside email's reach. 

That said, you're right that we don't have the synching procedure automated so that public is often a couple weeks behind. After the May round of conferences, we're going to set up a continuous integration box so that we can do a nightly or weekly push to public if safe.

**Comment by ryanmrichard** [comment]
There needs to be a way to avoid pushing certain parts though, otherwise it
undermines the scooping philosophy and we might as well not even have the
private repo

**Comment by wpoely86** [comment]
Why don't you keep the sensitive new code in separate branches of your (private) fork of the psi4public repo and only merge when the paper is ready? Or only use the private repo for that kind of stuff and push everything still straight to the public repo?
I think you're creating a lot of unneeded overhead with 2 repo's. git is decentralized by it's very nature, why not use it like that?

**Comment by ryanmrichard** [comment]
I think the short answer may be that a lot of the developers are still used
to version control models like SVN or CVS.

Honestly I think you have the right idea though, with git there really
isn't a need for two repositories for an open source code so long as we
adopt the accompanying philosophy.   It's now a matter of getting everyone
on board.

**Comment by andysim** [comment]
It’s not really an SVN/CVS thing, IMHO.  We were using Git for a very long time before making the public/private split and the core developers are extremely familiar with Git’s distributed nature.  The old way of developing Psi was to have a private repo (which used to be CVS, then SVN, then Git/SVN, before switching completely to Git) and to only release static tarballs every now and then.  Lori touched on the reason for the private repo - we need to be able to collaborate with each other but don’t want to release certain features until we’ve been able to write them up and test them.

The idea of having the private repo be a local one is fine if you’re working in isolation, but most of our code is developed collaboratively so we need a central place, like GitHub, to be able to store the repo.  Adding a public mirror was just a convenient way to provide more timely updates than static releases, and we have not been diligent enough in keeping this synced up.  If GitHub were to allow more fine-grained control of branch access, perhaps we could collapse down to one repo.  As things stand, I think that removing the private repo would prevent people from working together on new features that are to be released at a later date.

These issues were mooted a few years ago when we set the dual repo system up.  If there’s been a GitHub update in the intervening time that allows more fine-grained access, or if anybody has a better idea that doesn’t interrupt our workflow, then we’re always open to suggestions.

Andy.

**Comment by psi4** [comment]
Github also complicates things regarding private/public. It doesn’t allow mixing public and private branches in a repository. And it doesn’t allow you to make private a fork of a public repo, though there does seem to be an alternative: https://help.github.com/articles/duplicating-a-repository/ <https://help.github.com/articles/duplicating-a-repository/> . And in the beginning we didn’t want everyone to have to pay for storing private repositories if they wanted private forks (moot now since github offers private storage for scientists). That’s more of the history of how the current scheme came to be. I’m open to better schemes, but I think most of our problems can be solved by an automated public/private master sync when safe.

Lori

**Comment by wpoely86** [comment]
Well, maybe you should keep the new unpublished stuff in branches of the private repo and merge when ready. But only do the sensitive stuff in seperate branches. Bugfixes like this one should go straight to the master, combined with a daily sync between public and private?

**Comment by lothian** [comment]
I'm a bit confused by this discussion, because that is pretty much our
workflow already: prepare new methods on branches of the private repo,
merge them into the private master when they're ready/published, and
regularly sync private master with the public master.  The only delays
occur because the last step isn't fully automated, which seems to me a
minor issue for such a long conversation.

-TDC

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by loriab** [comment]
Original ``--version`` issue fixed now in public through sync from private. Greater issue of rigorous sync btwn public and private not yet resolved through CI, but we're trying to do the manual sync more frequently since there are now people actually looking at it.
