### ISSUE TITLE
2-Electron Integrals Issue

### ISSUE THREAD

**Issue by lucamontana** [psi4/psi4public#98]
Dear all, 
Is there any way to tell PSI4 to calculate the 2 electron integrals
for specified doubly occupied orbitals :   

set  docc        [8, 2]
set  freeze_core true   

How to get rid of a full 2 electron integral calculation for all basis functions per irrep but for those in my doubly occupied orbitals.
   
Calculation information:
      Number of atoms:                   6
      Number of AO shells:              24
      Number of SO shells:              21
      Number of primitives:              64
      Number of atomic orbitals:       50
      Number of basis functions:       48

      Number of irreps:                  2
      Integral cutoff                 1.00e-12
      Number of functions per irrep: [  33   15 ]

 OEINTS: Overlap, kinetic, potential, dipole, and quadrupole integrals
         stored in file 35.

      Computing two-electron integrals...done
      Computed 328662 non-zero two-electron integrals. 

Best Wishes
LUCA

**Comment by SebWouters** [comment]
Hi Luca,

It might not be the most readable code, but lines 635-660 of https://github.com/SebWouters/CheMPS2/blob/master/integrals/psi4plugins/dmrgscf.cc define different orbital spaces to perform transformations in. Also: If you really want to keep orbitals doubly occupied, it is better to take Coulomb and exchange contributions into account in a different way. Typically:
 1. Calculate the 1-RDM of docc orbitals in MO space (diagonal matrix with 2's and 0's).
 2. Rotate the 1-RDM to AO space with the orbital coefficients
 3. Contract the 1-RDM in AO space with the 2-electron integrals in AO space to the JK contribution of the Fock operator in the AO space
 4. Rotate the JK contribution in AO space to MO space with the orbital coefficients

This is done to avoid rotation of the 2-electron integrals from the AO space to the docc MO space.

What I described above is implemented in the routines
 1. buildQmatOCC - https://github.com/SebWouters/CheMPS2/blob/master/integrals/psi4plugins/dmrgscf.cc#L219
 2. buildJK - https://github.com/SebWouters/CheMPS2/blob/master/integrals/psi4plugins/dmrgscf.cc#L153

If you want a FCIDUMP file for an active space, I think the easiest would be to strip off the DMRG calculation from the dmrgscf.cc plugin, and copy paste the FCIDUMP print statements from the fcidump.cc plugin. The active space CASCI/DMRGCI Hamiltonian can be found in the HamDMRG object just AFTER line 778: https://github.com/SebWouters/CheMPS2/blob/master/integrals/psi4plugins/dmrgscf.cc#L778. And the localized active space CASCI/DMRGCI Hamiltonian can be found in the HamDMRG object just AFTER line 811: https://github.com/SebWouters/CheMPS2/blob/master/integrals/psi4plugins/dmrgscf.cc#L811, if you specified "LOC" as the active space type.

Best wishes,
Sebastian

**Comment by lucamontana** [comment]
Dear Sebastian, 
Thanks a lot for the detailed answer, but the problem with the FCIDUMP file is that i have no idea
how to tell PSI4 to give the final FCIDUMP after the HF calculation for a desired active space, as i see from test examples provided in CHEMPS2 , it gives automatically a FCIDUMP for 28 orbitals. 

How can i obtain a FCIDUMP for an active space using fcidump.cc plugin ???
You mention here : http://sebwouters.github.io/CheMPS2/inoutput.html  
" The σ-orbitals are kept frozen at the RHF/6-31G level of theory, and the active space consists of 28 RHF/6-31G π-orbitals"    but how did you keep the sigma orbitals frozen ?

This is for example done in molpro by :
{fci,core, 18,occ, 24
dump
}
But unfortunately in molpro it performs a full 2 electron calculation before giving the fcidump, some thing that i would like very much to avoid. 
 
Bests
Luca

**Comment by andysim** [comment]
Thank you for posting your very useful code snippets, Sebastian.  Another plugin that may be useful is the MOIntegrals plugin that comes with Psi4.  The command:

    ints.transform_tei(MOSpace::all, MOSpace::all, MOSpace::all, MOSpace::all);

can be replaced with:

    ints.transform_tei(MOSpace::occ, MOSpace::occ, MOSpace::occ, MOSpace::occ);

to generate only the occupied space integrals instead of the full set.  By default the integral transformation object will neglect frozen orbitals.

Andy.

**Comment by SebWouters** [comment]
Hi Luca,

    How can i obtain a FCIDUMP for a desired active space using fcidump.cc plugin ???
    You mention here : http://sebwouters.github.io/CheMPS2/inoutput.html

As I have told you in a previous mail, my FCIDUMP plugin to psi4 only dumps out the entire Hamiltonian. If you want a plugin which writes out the Hamiltonian for a given active space, I encourage you to write it yourself. You can either modify the FCIDUMP plugin, with the help of the DMRG-SCF plugin, so that you can print out specific active space Hamiltonians. As an alternative (which is the way I advise you to take), you can strip the DMRG-SCF plugin and copy in the FCI print lines from the FCIDUMP plugin.

     "The σ-orbitals are kept frozen at the RHF/6-31G level of theory, and the active space consists of 28 RHF/6-31G π-orbitals" but how did you keep the sigma orbitals frozen ?

The specific example of the pi-space of a polyene, where the doubly occupied RHF/6-31G sigma-orbitals are kept doubly frozen, can be done by using the DMRG-SCF plugin to do DMRG-CI calculations. As we have discussed, this can be done setting the variable ``dmrgscf_max_iter`` to 1 in the psi4 input file. You should also set ``dmrgscf_active_space`` to LOC and ``dmrgscf_loc_random`` to true, as well as use the ``Cs`` point group for the planar polyene. Using this point group is imperative to obtain localized pi-orbitals along the one-dimensional polyene. The number of frozen doubly occupied and active orbitals per irrep can then be specified in resp. the arrays ``frozen_docc`` and ``active``.

Best wishes,
Sebastian

**Comment by lucamontana** [comment]
Dear Sebastian,  
I think that the problem is rather related to PSI4 than dmrg. Just look at the example you provided for water molecule :

      Number of atoms:                   3
      Number of AO shells:               9
      Number of SO shells:               7
      Number of primitives:             22
      Number of atomic orbitals:        13
      Number of basis functions:        13

      Number of irreps:                  4
      Integral cutoff                 0.00e+00
      Number of functions per irrep: [   7    0    4    2 ]

 OEINTS: Overlap, kinetic, potential, dipole, and quadrupole integrals
         stored in file 35.

      Computing two-electron integrals...done
      Computed 1270 non-zero two-electron integrals.
        Stored in file 33.


Calling plugin fcidump.so.
	Presorting SO-basis two-electron integrals.
	Sorting File: SO Ints (nn|nn) nbuckets = 1
	Transforming the one-electron integrals and constructing Fock matrices
	Starting first half-transformation.
	Sorting half-transformed integrals.
	First half integral transformation complete.
	Starting second half-transformation.
	Two-electron integral transformation complete.
Created the file H2O.631G.FCIDUMP
-----------------------------------------------------------------------------------------------------------------------
As you see a full 2- electron integral calculation is performed for ALL basis functions (13)  and stored, just BEFORE fcidump starts with dumping !!!
I would like to circumvent this heavy calculation for the case of larger molecules.

Any way i try your advice but may i know at which line of fcidump.cc i have to copy and paste 
781-811   and  814-858 lines of dmrgscf.cc ?

Furthermore may i know what is the x matrix : "Number of variables in the x-matrix = 1032"
and what is nbuckets in : " SO Ints (nn|nn) nbuckets = 78"

ALL THE BEST
LUCA

**Comment by SebWouters** [comment]
Hi Luca,

(1) You of course always need to calculate the O(n^4) two-electron
integrals in the AO basis. The cost reduction is achieved by not performing
the total O(n^5) two-electron integral rotation.

(2) I think it is best if you figure out which lines to copy where. Else I
might as well have written the plugin. The reason why I answer all these
questions, instead of doing it myself in 10 min, is because I hope you
learn something from my hints.

(3) The number of variables in the x-matrix is the number of independent
parameters which characterize an orthogonal orbital rotation. It are the
parameters x from the 1981 Siegbahn paper on CASSCF. They connect only
orbitals which belong to the same irreducible representation b.t.w.

(4) I have no idea what the buckets are in the integral rotation.

Best,
Sebastian


2015-05-26 2:26 GMT+02:00 lucamontana <notifications@github.com>:

> Dear Sebastian,
>
> I think that the problem is rather related to PSI4 than dmrg. Just look at
> the example you provided for water molecule :
>
>   Number of atoms:                   3
>   Number of AO shells:               9
>   Number of SO shells:               7
>   Number of primitives:             22
>   Number of atomic orbitals:        13
>   Number of basis functions:        13
>
>   Number of irreps:                  4
>   Integral cutoff                 0.00e+00
>   Number of functions per irrep: [   7    0    4    2 ]
>
> OEINTS: Overlap, kinetic, potential, dipole, and quadrupole integrals
> stored in file 35.
>
>   Computing two-electron integrals...done
>   Computed 1270 non-zero two-electron integrals.
>     Stored in file 33.
>
> Calling plugin fcidump.so.
> Presorting SO-basis two-electron integrals.
> Sorting File: SO Ints (nn|nn) nbuckets = 1
> Transforming the one-electron integrals and constructing Fock matrices
> Starting first half-transformation.
> Sorting half-transformed integrals.
> First half integral transformation complete.
> Starting second half-transformation.
> Two-electron integral transformation complete.
> Created the file H2O.631G.FCIDUMP
>
> As you see a full 2- electron integral calculation is performed for ALL
> basis functions (13) and stored, just BEFORE fcidump starts with dumping !!!
> I would like to circumvent this heavy calculation for the case of larger
> molecules.
>
> Any way i try your advice but may i know at which line of fcidump.cc i
> have to copy and paste
> 781-811 and 814-858 lines of dmrgscf.cc ?
>
> Furthermore may i know what is the x matrix : "Number of variables in the
> x-matrix = 1032"
> and what is nbuckets in : " SO Ints (nn|nn) nbuckets = 78"
>
> ALL THE BEST
> LUCA
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psi4/psi4public/issues/98#issuecomment-105341330>.
>



-- 
****************************************************

  dr. ir. Sebastian Wouters
  Fellow of the Belgian American Educational Foundation
  Princeton University
  (address) Department of Chemistry
            Frick Laboratory 351
            Princeton, NJ 08544, USA
  (e-mail)  sebastianwouters@gmail.com

****************************************************

**Comment by lucamontana** [comment]
Dear Sebastian, 

I really appreciate your hints and helps, but i have to say that after some days of intense testing and checking, it seems to me that unfortunately DMRG is difficult to apply on large molecules (400 atoms) unless full 2-electron integral calculation is avoided. Furthermore i observe that CHEMPS2 becomes very slow once you choose a better basis set (cc-pvtz  vs cc-pvdz) .

"The cost reduction is achieved by not performing the total O(n^5) two-electron integral rotation."

How can i achieve this ? By following those hints in your previous answers ? 
I think, avoiding two-electron integral rotations is some thing which should be done in PSI4 rather than in the fcidump plugin modification.

Best wishes
Luca

**Comment by CDSherrill** [comment]
Hi Luca,

Yes, Sebastian is right, freezing molecular orbitals unfortunately does not allow you to reduce the number of atomic orbital integrals to compute.  That's because every atomic orbital integral can contribute to a molecular orbital integral, unless special tricks are used.  Such tricks are not really trivial and require some significant work to utilize.

David
